version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://stationf:adminrootnimda@cluster0.ypxwr.mongodb.net/Cluster0?retryWrites=true&w=majority
